services:
  qopy:
    build: .
    container_name: qopy_app
    ports:
      - "127.0.0.1:3001:5000"
    env_file:
      - server/.env
    networks:
      - infra_internal
    volumes:
      - ./server/uploads:/app/server/uploads

networks:
  infra_internal:
    external: true
