version: "3.8"
services:
  qopy:
    build: .
    container_name: qopy_app
    ports:
      - "127.0.0.1:3001:5000"
    env_file:
      - server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server/uploads:/app/server/uploads
